import { useState, useRef, useEffect } from 'react'

function Message({ role, text, time }) {
  const isUser = role === 'user'
  return (
    <div className={`flex gap-3 ${isUser ? 'flex-row-reverse' : ''}`}>
      <div className={`w-8 h-8 rounded-lg shrink-0 flex items-center justify-center text-xs font-bold ${
        isUser ? 'bg-indigo-600 text-white' : 'bg-zinc-700 text-zinc-300'
      }`}>
        {isUser ? 'You' : 'AI'}
      </div>
      <div className={`max-w-[75%] ${isUser ? 'items-end' : 'items-start'} flex flex-col gap-1`}>
        <div className={`rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
          isUser
            ? 'bg-indigo-600 text-white rounded-tr-sm'
            : 'bg-zinc-800 text-zinc-200 rounded-tl-sm'
        }`}>
          {text}
        </div>
        <span className="text-[11px] text-zinc-600 px-1">{time}</span>
      </div>
    </div>
  )
}

const suggestions = [
  "Explain Newton's laws of motion simply",
  "What is the difference between RAM and ROM?",
  "Help me create a study schedule for 3 exams",
  "Summarize the causes of World War I",
]

export default function Chat({ user }) {
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const bottomRef = useRef(null)
  const textareaRef = useRef(null)

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, loading])

  const now = () => new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })

  const sendMessage = (text) => {
    const query = text || input.trim()
    if (!query || loading) return

    setInput('')
    setMessages(prev => [...prev, { id: Date.now(), role: 'user', text: query, time: now() }])
    setLoading(true)

    // Simulate AI response
    setTimeout(() => {
      const responses = [
        `Great question! Let me break that down for you.\n\n"${query}" is a topic worth exploring carefully. In a real app, this is where the AI model (like Claude or GPT) would provide a detailed, accurate answer based on your specific question.\n\nFor now, keep studying — you're doing great! 🎓`,
        `That's an interesting topic. Here's a quick overview:\n\nIn a production version of StudyAI, this response would be generated by an actual AI model connected via API. Your question about "${query}" would get a thorough explanation with examples.\n\nKeep asking questions — curiosity is the foundation of learning!`,
        `Good thinking! Here's what you should know:\n\nThis is a demo response. The real StudyAI would connect to an AI backend to answer "${query}" with accurate, subject-specific information.\n\nDon't stop here — dig deeper into the topic!`,
      ]
      const reply = responses[Math.floor(Math.random() * responses.length)]
      setMessages(prev => [...prev, { id: Date.now() + 1, role: 'ai', text: reply, time: now() }])
      setLoading(false)
    }, 1200 + Math.random() * 800)
  }

  const handleKey = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <div className="flex flex-col h-full max-h-[calc(100vh-56px)]">
      {/* Header */}
      <div className="px-6 py-4 border-b border-zinc-800 bg-zinc-900/50 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center">
            <svg className="w-5 h-5 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
            </svg>
          </div>
          <div>
            <h1 className="text-white font-semibold text-sm">Study AI Assistant</h1>
            <div className="flex items-center gap-1.5">
              <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
              <p className="text-xs text-zinc-500">Ready to help you learn</p>
            </div>
          </div>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 sm:px-6 py-6 space-y-5">
        {messages.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-center gap-6 py-12">
            <div className="w-16 h-16 rounded-2xl bg-indigo-600/20 border border-indigo-500/20 flex items-center justify-center">
              <svg className="w-8 h-8 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <div>
              <h2 className="text-white font-semibold text-lg">
                Hey {user?.name?.split(' ')[0] || 'there'}, what are you studying?
              </h2>
              <p className="text-zinc-500 text-sm mt-1">Ask me anything — I'm here to help you understand it.</p>
            </div>

            <div className="grid sm:grid-cols-2 gap-2 w-full max-w-lg">
              {suggestions.map(s => (
                <button
                  key={s}
                  onClick={() => sendMessage(s)}
                  className="bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 text-zinc-300 hover:text-white text-sm text-left px-4 py-3 rounded-xl transition-all"
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
        ) : (
          messages.map(msg => (
            <Message key={msg.id} {...msg} />
          ))
        )}

        {loading && (
          <div className="flex gap-3">
            <div className="w-8 h-8 rounded-lg bg-zinc-700 flex items-center justify-center text-xs font-bold text-zinc-300 shrink-0">AI</div>
            <div className="bg-zinc-800 rounded-2xl rounded-tl-sm px-4 py-3 flex gap-1.5 items-center">
              <div className="w-2 h-2 bg-zinc-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
              <div className="w-2 h-2 bg-zinc-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
              <div className="w-2 h-2 bg-zinc-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
            </div>
          </div>
        )}

        <div ref={bottomRef} />
      </div>

      {/* Input area */}
      <div className="px-4 sm:px-6 py-4 border-t border-zinc-800 bg-zinc-900/50 shrink-0">
        <div className="flex gap-2 items-end bg-zinc-800 border border-zinc-700 rounded-2xl px-4 py-3 focus-within:border-indigo-500 transition-all">
          <textarea
            ref={textareaRef}
            rows={1}
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={handleKey}
            placeholder="Ask a question... (Enter to send, Shift+Enter for newline)"
            className="flex-1 bg-transparent text-sm text-white placeholder-zinc-500 outline-none resize-none leading-relaxed"
            style={{ maxHeight: '120px' }}
          />
          <button
            onClick={() => sendMessage()}
            disabled={!input.trim() || loading}
            className="bg-indigo-600 hover:bg-indigo-500 disabled:bg-zinc-700 disabled:cursor-not-allowed text-white rounded-xl w-9 h-9 flex items-center justify-center transition-colors shrink-0"
          >
            <svg className="w-4 h-4 rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </button>
        </div>
        <p className="text-[11px] text-zinc-600 mt-2 text-center">
          AI responses are simulated — connect an AI API key to enable real answers.
        </p>
      </div>
    </div>
  )
}